services:
  - type: web
    name: voicescript
    runtime: python
    pythonVersion: "3.11.0"
    nativePackages:
      - ffmpeg
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 900 --workers 1 --threads 2"
    plan: free
    envVars:
      - key: WHISPER_MODEL
        value: tiny
      - key: GUNICORN_CMD_ARGS
        value: "--workers 1 --threads 2 --timeout 900 --keep-alive 30"
