services:
  - type: web
    name: voicescript
    runtime: python
    pythonVersion: "3.11.0"
    nativePackages:
      - ffmpeg
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 300 --workers 1"
    plan: free
    envVars:
      - key: WHISPER_MODEL
        value: tiny
